import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import Loading from "@/app/loading";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppProvider } from "@/app/app";
import "@ant-design/v5-patch-for-react-19";
import { SidebarProvider } from "@/context/SidebarContext";
import { ThemeProvider } from "@/context/ThemeContext";

const outfit = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} dark:bg-gray-900`}>
        <Suspense fallback={<Loading />}>
          <AntdRegistry>
            <ThemeProvider>
              <SidebarProvider>
                <AppProvider>{children}</AppProvider>
              </SidebarProvider>
            </ThemeProvider>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
